spring:
  #配置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bilibili?serverTimezone=UTC
      username: root
      password: 250628

  redis:
    port: 6379
    host: localhost
  #配置缓存数据的过期时间
  cache:
    redis:
      time-to-live: 1800000

  #配置上传文件的大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 9090
  tomcat:
    connection-timeout: 60000


#配置日志信息到本地磁盘
logging:
  file:
    name: D:/java_SpringBoot/Project/Like_BiliBili_log
  level:
    com.grazy.mapper: debug


#RocketMq
Rocketmq:
  name:
    server:
      address: 127.0.0.1:9876


#FastDFS
fdfs:
  tracker-list: 192.168.195.100:22122
  http:
    storage-add: http://192.168.195.100:8888/group1/


#ElasticSearch
elasticsearch:
  url: 192.168.195.100:9200
