spring:
  #配置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bilibili?serverTimezone=UTC
      username: root
      password: 250628

server:
  port: 9090


#配置日志信息到本地磁盘
logging:
  file:
    name: D:/java_SpringBoot/Project/Like_BiliBili_log
  level:
    com.grazy.mapper: debug


#RocketMq
Rocketmq:
  name:
    server:
      address: localhost/
